### ISSUE TITLE
Posted Photos on blog have no margin-left

### ISSUE THREAD

**Issue by musantro** [Kikobeats/bloggy#4]
Somewhere inside the code:

```
.post-content .full-img {
    width: calc(100% + 60px)
}
```

I think it's in `bloggy.css` but I'm not 100 % sure. 

I think erasing those `60px` will fix this issue.

**Comment by Kikobeats** [comment]
I don't understand, provide a screenshot pls

**Comment by musantro** [comment]
![image](https://cloud.githubusercontent.com/assets/13135993/12529932/69ce37ca-c1cc-11e5-96b4-0a2a05a836a4.png)

As you can see, there is no margin-left on the main photo. These are the CSS attributes for this photo

```
.post-content .full-img {
    width: calc(100% + 60px);
    margin-left: -60px;
}
```

Here is how it should be:

![image](https://cloud.githubusercontent.com/assets/13135993/12529935/7f1b56d0-c1cc-11e5-9692-f7d87467cb53.png)

```
.post-content .full-img {
    width: calc(100%);
}
```

This issue only appears in large width windows, not in mobile, for example.

**Comment by Kikobeats** [comment]
Is not a bug, is a intentional effect from the original theme. See whatever
Ghost blog entry

**Comment by musantro** [comment]
Oops.

Then, as a suggestion, do you think it's better to have a margin-left instead of none?

**Comment by Kikobeats** [comment]
The point of bloggy is provide a basecode for have a Ghost theme based in the ghost blog theme. Later you can adapt it as you like. So in this case should be easy avoid the margin left effect just providing a custom css/js in the blog header injection.

**Comment by musantro** [comment]
Thanks!
